<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Kare.Cloud.Copilot</RootNamespace>
    <NoWarn>$(NoWarn);GHCP001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Kare.Abstractions/Kare.Abstractions.csproj" />
    <ProjectReference Include="../Kare.Core/Kare.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitHub.Copilot.SDK" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

</Project>
