<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Kare.Inference.OnnxGenAI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Kare.Abstractions/Kare.Abstractions.csproj" />
    <ProjectReference Include="../Kare.Core/Kare.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

</Project>
