using System.ComponentModel.DataAnnotations;

namespace Kare.Core.Options;

/// <summary>Explicit local, Copilot, and Foundry routing policy.</summary>
public sealed class RoutePolicyOptions
{
    /// <summary>Configuration section name.</summary>
    public const string SectionName = "Kare:Routing";

    /// <summary>Wire model name that always selects the local SLM.</summary>
    [Required]
    public string LocalModelId { get; set; } = "kare-local";

    /// <summary>Wire model name that selects the low-cost Copilot model pool.</summary>
    [Required]
    public string LightModelId { get; set; } = "kare-fast";

    /// <summary>Wire model name that explicitly selects the configured heavy Copilot model.</summary>
    [Required]
    public string CloudModelId { get; set; } = "kare-copilot";

    /// <summary>Wire model name that explicitly selects a configured Foundry deployment.</summary>
    [Required]
    public string ComplexModelId { get; set; } = "kare-complex";

    /// <summary>Wire model name that applies the deterministic automatic policy.</summary>
    [Required]
    public string AutomaticModelId { get; set; } = "kare-auto";

    /// <summary>
    /// Enables automatic cloud selection for <see cref="AutomaticModelId"/>.
    /// This is off by default because cloud calls are billable.
    /// </summary>
    public bool EnableAutomaticCloudEscalation { get; set; }

    /// <summary>
    /// Enables the single-mode HydraFusion cascade: cached route, local Qwen gate,
    /// then ordered cloud escalation.
    /// </summary>
    public bool EnableCascadeEscalation { get; set; }

    /// <summary>Maximum user-request characters shown to the local cascade gate.</summary>
    [Range(1_024, 32_768)]
    public int CascadeDecisionMaxInputCharacters { get; set; } = 1_024;

    /// <summary>Maximum tokens generated by the local cascade gate.</summary>
    [Range(32, 1_024)]
    public int CascadeDecisionMaxOutputTokens { get; set; } = 32;

    /// <summary>
    /// Maximum tokens generated when caller tools require a cloud target and the gate only
    /// needs to return a target identifier.
    /// </summary>
    [Range(4, 64)]
    public int CascadeToolDecisionMaxOutputTokens { get; set; } = 8;

    /// <summary>Maximum tokens generated after a tool-bearing request selects local inference.</summary>
    [Range(16, 256)]
    public int CascadeLocalAnswerMaxOutputTokens { get; set; } = 64;

    /// <summary>
    /// Runs a bounded local result judge after a non-streaming cloud draft. Disabled by default
    /// until task-class quality measurements justify the extra local call.
    /// </summary>
    public bool EnableCascadeResultJudge { get; set; }

    /// <summary>Maximum tokens generated by the bounded local result judge.</summary>
    [Range(32, 256)]
    public int CascadeJudgeMaxOutputTokens { get; set; } = 32;

    /// <summary>
    /// Runs one read-only cross-provider critique and one revision for eligible
    /// non-streaming text drafts.
    /// </summary>
    public bool EnableCascadeCritique { get; set; }

    /// <summary>Maximum request and draft characters sent to the critic.</summary>
    [Range(1_024, 32_768)]
    public int CascadeCritiqueMaxInputCharacters { get; set; } = 2_048;

    /// <summary>Maximum tokens generated by the bounded critic.</summary>
    [Range(32, 512)]
    public int CascadeCritiqueMaxOutputTokens { get; set; } = 128;

    /// <summary>
    /// Character threshold above which the automatic route selects the light Copilot pool.
    /// </summary>
    [Range(1_024, 10_000_000)]
    public int ModeratePromptCharacterThreshold { get; set; } = 6_000;

    /// <summary>Character threshold above which automatic routing selects the complex route.</summary>
    [Range(1_024, 10_000_000)]
    public int ComplexPromptCharacterThreshold { get; set; } = 24_000;

}
