<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Kare.Inference.GenieX</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Kare.Abstractions/Kare.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

</Project>
