<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>copilot-kare</AssemblyName>
    <RootNamespace>Kare.CopilotLauncher</RootNamespace>
    <RuntimeIdentifiers>linux-x64;linux-arm64;win-x64;win-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <SelfContained Condition="'$(RuntimeIdentifier)' != ''">true</SelfContained>
    <UseAppHost>true</UseAppHost>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kare.Abstractions\Kare.Abstractions.csproj" />
    <InternalsVisibleTo Include="Kare.Tests" />
  </ItemGroup>

</Project>
